// AUTO-GENERATED by scripts/generate-methods.ts — do not edit.
import type { paths } from "./schema.js";
import type createFetchClient from "openapi-fetch";

type Client = ReturnType<typeof createFetchClient<paths>>;

type ReqBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends { requestBody: { content: { "application/json": infer B } } } ? B : never;

type ResBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends { responses: { 200: { content: { "application/json": infer R } } } } ? R : paths[P][M] extends { responses: { 201: { content: { "application/json": infer R } } } } ? R : unknown;

export interface SomaMethods {
  /** Get credit balance Free. */
  getBalance(): Promise<{ data?: ResBody<"/v1/balance", "get">; error?: unknown; response: Response }>;
  /** Intake a todo Auth required. Free. */
  createTodo(body: ReqBody<"/v1/todo", "post">): Promise<{ data?: ResBody<"/v1/todo", "post">; error?: unknown; response: Response }>;
  /** List todos Auth required. Free. */
  listTodos(): Promise<{ data?: ResBody<"/v1/todo", "get">; error?: unknown; response: Response }>;
  /** Get a todo Auth required. Free. */
  getTodo(id: string): Promise<{ data?: ResBody<"/v1/todo/{id}", "get">; error?: unknown; response: Response }>;
  /** Advance a todo's state Auth required. Free. */
  advanceTodo(id: string, body: ReqBody<"/v1/todo/{id}/advance", "post">): Promise<{ data?: ResBody<"/v1/todo/{id}/advance", "post">; error?: unknown; response: Response }>;
  /** Comment on a todo Auth required. Free. */
  commentTodo(id: string, body: ReqBody<"/v1/todo/{id}/comment", "post">): Promise<{ data?: ResBody<"/v1/todo/{id}/comment", "post">; error?: unknown; response: Response }>;
  /** Deliver an artifact Auth required. Costs 100 credits on metered keys (admin keys free). */
  deliverTodo(id: string, body: ReqBody<"/v1/todo/{id}/deliver", "post">): Promise<{ data?: ResBody<"/v1/todo/{id}/deliver", "post">; error?: unknown; response: Response }>;
  /** Fund a prepaid card Auth required. Costs 50 credits on metered keys (admin keys free). */
  fundTodo(id: string, body: ReqBody<"/v1/todo/{id}/fund", "post">): Promise<{ data?: ResBody<"/v1/todo/{id}/fund", "post">; error?: unknown; response: Response }>;
}

export function bindMethods(client: Client): SomaMethods {
  return {
    getBalance() {
      return client.GET("/v1/balance" as any, {  } as any) as any;
    },
    createTodo(body) {
      return client.POST("/v1/todo" as any, { body } as any) as any;
    },
    listTodos() {
      return client.GET("/v1/todo" as any, {  } as any) as any;
    },
    getTodo(id) {
      return client.GET("/v1/todo/{id}" as any, { params: { path: { id } } } as any) as any;
    },
    advanceTodo(id, body) {
      return client.POST("/v1/todo/{id}/advance" as any, { params: { path: { id } }, body } as any) as any;
    },
    commentTodo(id, body) {
      return client.POST("/v1/todo/{id}/comment" as any, { params: { path: { id } }, body } as any) as any;
    },
    deliverTodo(id, body) {
      return client.POST("/v1/todo/{id}/deliver" as any, { params: { path: { id } }, body } as any) as any;
    },
    fundTodo(id, body) {
      return client.POST("/v1/todo/{id}/fund" as any, { params: { path: { id } }, body } as any) as any;
    },
  };
}
