#!/usr/bin/env bun
/**
 * Generate typed convenience methods from the Soma OpenAPI spec.
 * Reads the locally-emitted spec, extracts every operation, and emits src/methods.ts
 * with a SomaMethods interface and bindMethods() function.
 *
 * Adapted from VidJutsu's generator, extended to handle PATH parameters (Soma's
 * /v1/todo/{id}/… routes) in addition to body/query.
 *
 * Usage:
 *   bun scripts/generate-methods.ts                           # default: ../../spec/openapi/spec.json
 *   bun scripts/generate-methods.ts --local path/to/spec.json # override
 */
import { writeFileSync } from "fs";
import { resolve } from "path";
import { PRICING } from "../../../core/domain/pricing";

const DEFAULT_SPEC = resolve(import.meta.dir, "../../../spec/openapi/spec.json");
const outPath = resolve(import.meta.dir, "../src/methods.ts");

// Per-operation metadata. Soma has a single shared gateway key (no per-call credits),
// so this is auth-level only — kept as a table so it can grow with the contract.
const ROUTE_META: Record<string, { auth: string }> = {
  createTodo: { auth: "authenticated" },
  listTodos: { auth: "authenticated" },
  getTodo: { auth: "authenticated" },
  commentTodo: { auth: "authenticated" },
  advanceTodo: { auth: "authenticated" },
  deliverTodo: { auth: "authenticated" },
  fundTodo: { auth: "authenticated" },
};

async function loadSpec(): Promise<any> {
  const localIdx = process.argv.indexOf("--local");
  const file = Bun.file(
    localIdx !== -1 && process.argv[localIdx + 1] ? process.argv[localIdx + 1] : DEFAULT_SPEC,
  );
  return file.json();
}

interface Operation {
  path: string;
  method: string; // GET, POST, PUT, DELETE
  operationId: string;
  summary: string;
  pathParams: string[];
  queryParams: string[];
  requestBodyRef: string | null;
  hasSuccessBody: boolean;
}

function extractOperations(spec: any): Operation[] {
  const ops: Operation[] = [];
  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [method, opDef] of Object.entries(methods as any)) {
      if (method === "options" || method === "parameters") continue;
      const op = opDef as any;
      if (!op.operationId) continue;

      const params = (op.parameters ?? []) as Array<{ name: string; in: string }>;
      const pathParams = params.filter((p) => p.in === "path").map((p) => p.name);
      const queryParams = params.filter((p) => p.in === "query").map((p) => p.name);

      const requestBodyRef =
        op.requestBody?.content?.["application/json"]?.schema?.$ref?.replace(
          "#/components/schemas/",
          "",
        ) ?? null;

      let hasSuccessBody = false;
      for (const [status, resDef] of Object.entries(op.responses ?? {})) {
        const n = parseInt(status);
        if (n >= 200 && n < 300 && (resDef as any).content?.["application/json"]) {
          hasSuccessBody = true;
          break;
        }
      }

      ops.push({
        path,
        method: method.toUpperCase(),
        operationId: op.operationId,
        summary: op.summary ?? "",
        pathParams,
        queryParams,
        requestBodyRef,
        hasSuccessBody,
      });
    }
  }
  return ops;
}

function emit(ops: Operation[]): string {
  const L: string[] = [
    "// AUTO-GENERATED by scripts/generate-methods.ts — do not edit.",
    'import type { paths } from "./schema.js";',
    'import type createFetchClient from "openapi-fetch";',
    "",
    "type Client = ReturnType<typeof createFetchClient<paths>>;",
    "",
    'type ReqBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends { requestBody: { content: { "application/json": infer B } } } ? B : never;',
    "",
    'type ResBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends { responses: { 200: { content: { "application/json": infer R } } } } ? R : paths[P][M] extends { responses: { 201: { content: { "application/json": infer R } } } } ? R : unknown;',
    "",
    "export interface SomaMethods {",
  ];

  for (const op of ops) {
    const meta = ROUTE_META[op.operationId];
    const doc = [op.summary || op.operationId];
    if (meta?.auth === "authenticated") doc.push("Auth required.");
    const cost = PRICING[op.operationId] ?? 0;
    doc.push(cost > 0 ? `Costs ${cost} credits on metered keys (admin keys free).` : "Free.");
    L.push(`  /** ${doc.join(" ")} */`);

    const args: string[] = [];
    for (const p of op.pathParams) args.push(`${p}: string`);
    if (op.requestBodyRef) args.push(`body: ReqBody<"${op.path}", "${op.method.toLowerCase()}">`);

    const ret = `Promise<{ data?: ResBody<"${op.path}", "${op.method.toLowerCase()}">; error?: unknown; response: Response }>`;
    L.push(`  ${op.operationId}(${args.join(", ")}): ${ret};`);
  }
  L.push("}", "");

  L.push("export function bindMethods(client: Client): SomaMethods {");
  L.push("  return {");
  for (const op of ops) {
    const argNames: string[] = [...op.pathParams];
    if (op.requestBodyRef) argNames.push("body");
    const pathObj = op.pathParams.length
      ? `params: { path: { ${op.pathParams.join(", ")} } }`
      : "";
    const bodyObj = op.requestBodyRef ? "body" : "";
    const opts = [pathObj, bodyObj].filter(Boolean).join(", ");
    L.push(`    ${op.operationId}(${argNames.join(", ")}) {`);
    L.push(`      return client.${op.method}("${op.path}" as any, { ${opts} } as any) as any;`);
    L.push(`    },`);
  }
  L.push("  };");
  L.push("}", "");
  return L.join("\n");
}

const spec = await loadSpec();
const ops = extractOperations(spec);
console.log(`Parsed ${ops.length} operations`);
const content = emit(ops);
writeFileSync(outPath, content);
console.log(`Wrote methods.ts (${content.split("\n").length} lines)`);
